name: portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: echo "Hello !"
      - name: Run ls -l
        run: ls -l